// 네이버 클라우드 콘솔에서 발급한 Maps JavaScript API Client ID를 입력하세요.
// 예: const NAVER_MAP_CLIENT_ID = '발급받은_CLIENT_ID';
const NAVER_MAP_CLIENT_ID = 'YOUR_NAVER_MAP_CLIENT_ID';
const routes=[
 {tag:'MIX · 추천 01',style:'mix',title:'바다와 동네 사이, 포항의 첫 장면',desc:'대표 명소와 로컬 쉼터를 자연스럽게 잇는 코스',time:'2박 3일',distance:'48.2 km',price:1764000,places:[['★','영일대 해수욕장','4.8 km'],['○','송도 솔밭','6.2 km'],['★','스페이스워크','9.4 km'],['○','청림동 카페','2.8 km']]},
 {tag:'LOCAL · 추천 02',style:'local',title:'파도 따라 천천히, 로컬의 주말',desc:'사람이 붐비지 않는 해안과 동네 식당 중심',time:'2박 3일',distance:'39.8 km',price:1586000,places:[['○','송도 솔밭','6.2 km'],['○','연오랑세오녀 테마공원','11.8 km'],['★','호미곶','24.5 km'],['○','구룡포 골목','8.1 km']]},
 {tag:'TOURIST · 추천 03',style:'tourist',title:'처음이라면 꼭, 포항 클래식',desc:'포항을 대표하는 장면을 빠짐없이 만나는 코스',time:'2박 3일',distance:'62.4 km',price:1832000,places:[['★','스페이스워크','9.4 km'],['★','영일대','4.8 km'],['★','호미곶','24.5 km'],['★','죽도시장','3.1 km']]},
 {tag:'ACTIVE · 추천 04',style:'active',title:'걷고 오르고, 바람을 타는 하루',desc:'액티비티와 전망 포인트를 밀도 있게 연결',time:'2박 3일',distance:'54.7 km',price:1718000,places:[['★','스페이스워크','9.4 km'],['○','내연산 트레킹','28.4 km'],['★','영일대','4.8 km'],['○','칠포 해변','17.3 km']]},
 {tag:'LOCAL · 추천 05',style:'local',title:'구룡포에서 만나는 포항의 결',desc:'근대문화 골목과 현지 식탁을 따라가는 코스',time:'2박 3일',distance:'58.1 km',price:1638000,places:[['★','구룡포 일본인 가옥거리','36.6 km'],['○','구룡포항','37.2 km'],['○','대보항','40.3 km'],['★','호미곶','24.5 km']]}
];
const places=[...new Map(routes.flatMap(r=>r.places.map(p=>[p[1],{name:p[1],type:p[0],distance:p[2],route:r.title}]))).values()];
const grid=document.querySelector('#routeGrid'), searchInput=document.querySelector('#placeSearch'), searchResults=document.querySelector('#searchResults');
const money=n=>`₩${n.toLocaleString('ko-KR')}`;
function renderRoutes(list=routes){grid.innerHTML=list.map((r,i)=>`<article class="route-card ${i===0?'featured':''}"><div class="route-top"><div><span class="route-tag">${r.tag}</span><h3>${r.title}</h3><p>${r.desc}</p></div><span>♡</span></div><div class="route-line"></div><div class="route-stats"><span>전체 이동 <strong>${r.distance}</strong></span><span>4명 예상 비용 <strong>${money(r.price)}</strong></span></div><div class="route-places">${r.places.map(p=>`<span class="place ${p[0]==='★'?'star':'circle'}">${p[0]} ${p[1]} <small>${p[2]}</small></span>`).join('')}</div><button class="save" aria-label="일정 저장">＋</button></article>`).join('')}
function renderSearch(query=''){const q=query.trim().toLowerCase();const found=places.filter(p=>!q||p.name.toLowerCase().includes(q)||p.route.toLowerCase().includes(q));searchResults.innerHTML=found.length?found.map(p=>`<button class="search-result"><span class="result-symbol">${p.type}</span><span><b>${p.name}</b><small>${p.route}</small></span><strong>${p.distance}</strong></button>`).join(''):`<p class="empty">검색 결과가 없어요. 예: 영일대, 호미곶, 카페</p>`;}
renderRoutes();renderSearch();
const plans={'1일차':[],'2일차':[],'3일차':[]};let currentDay='1일차';
async function searchNaverMap(){const query=document.querySelector('#builderSearch').value.trim();if(!query){showToast('검색할 장소나 카페를 입력해주세요.');return}const box=document.querySelector('#builderResults');box.innerHTML='<p class="empty">네이버에서 장소를 찾고 있어요...</p>';try{const response=await fetch(`/api/search?query=${encodeURIComponent(`${query} 포항`)}`);const data=await response.json();if(!response.ok)throw new Error(data.error);box._items=data.items||[];box.innerHTML=box._items.length?box._items.map((p,i)=>{const selected=plans[currentDay].some(x=>x.name===p.name);return `<button class="builder-result${selected?' is-selected':''}" data-index="${i}"><span class="result-symbol">⌖</span><span><b>${p.name}</b><small>${p.category||'장소'} · ${p.address||'주소 정보 없음'}</small></span><span class="add-mark">${selected?'−':'＋'}</span></button>`}).join(''):'<p class="empty">검색 결과가 없어요.</p>'}catch(error){box.innerHTML=`<p class="empty">${error.message}</p>`}}
function renderItinerary(){const list=plans[currentDay];document.querySelector('#selectedDay').textContent=`${currentDay} 일정`;document.querySelector('#selectedCount').textContent=`${list.length}곳`;document.querySelector('#itinerary').innerHTML=list.length?list.map((p,i)=>`<div class="itinerary-item"><span class="order">${i+1}</span><span><b>${p.name}</b><small>${p.category||'네이버 장소'} · ${p.address||'포항'}</small></span><button class="focus-place" data-index="${i}">지도에 표시</button></div>`).join(''):`<p class="empty">검색한 장소를 일정에 추가해보세요.</p>`}
renderItinerary();
async function loadNaverMap(){try{const config=await fetch('/api/config').then(r=>r.json());const clientId=config.naverMapClientId;if(!clientId){showToast('Vercel에 NAVER_MAP_CLIENT_ID를 등록해주세요.');return}const script=document.createElement('script');script.src=`https://oapi.map.naver.com/openapi/v3/maps.js?ncpKeyId=${encodeURIComponent(clientId)}`;script.async=true;script.onload=()=>{window.naverMap=new naver.maps.Map('naverMap',{center:new naver.maps.LatLng(36.0190,129.3435),zoom:11,draggable:true,scrollWheel:true,zoomControl:true,zoomControlOptions:{position:naver.maps.Position.TOP_RIGHT}});document.querySelector('#naverMap .map-grid')?.remove();document.querySelectorAll('#naverMap .map-pin').forEach(x=>x.remove());document.querySelector('#naverMap .map-caption small').textContent='네이버 지도 API 연결됨';};script.onerror=()=>showToast('네이버 지도 API를 불러오지 못했어요. Client ID와 허용 도메인을 확인해주세요.');document.head.appendChild(script)}catch(error){showToast('네이버 지도 설정을 불러오지 못했어요.')}}
const recommendationCoordinates={'영일대 해수욕장':[36.0560,129.3780],'영일대':[36.0560,129.3780],'송도 솔밭':[36.0320,129.3650],'스페이스워크':[36.0615,129.3980],'청림동 카페':[35.9970,129.4050],'연오랑세오녀 테마공원':[35.9770,129.4370],'호미곶':[36.0760,129.5660],'구룡포 골목':[35.9910,129.5510],'죽도시장':[36.0370,129.3650],'내연산 트레킹':[36.2720,129.3470],'칠포 해변':[36.1570,129.3810],'구룡포 일본인 가옥거리':[35.9910,129.5510],'구룡포항':[35.9900,129.5570],'대보항':[36.0550,129.5640]};let recommendationMarkers=[];function toggleRecommendationPlace(name){const p=places.find(x=>x.name===name)||{name,type:'★',distance:'추천 코스'};const existing=plans[currentDay].find(x=>x.name===name);if(existing){if(existing.marker)existing.marker.setMap(null);plans[currentDay]=plans[currentDay].filter(x=>x.name!==name);showToast(`${name}을(를) ${currentDay}에서 제거했어요.`)}else{const coords=recommendationCoordinates[name];const location=coords?new naver.maps.LatLng(coords[0],coords[1]):null;const place={name,distance:p.distance,address:'포항 추천 여행지',category:'추천 여행지',location};if(location)place.marker=new naver.maps.Marker({map:window.naverMap,position:location,title:`${name} · 클릭하여 일정에 추가/제거`});plans[currentDay].push(place);showToast(`${name}을(를) ${currentDay}에 추가했어요.`)}renderItinerary()}function renderRecommendationMarkers(){recommendationMarkers.forEach(marker=>marker.setMap(null));recommendationMarkers=[];const unique=[...new Map(places.map(p=>[p.name,p])).values()];unique.forEach(p=>{const coords=recommendationCoordinates[p.name];if(!coords)return;const marker=new naver.maps.Marker({map:window.naverMap,position:new naver.maps.LatLng(coords[0],coords[1]),title:`${p.name} · 추천 여행지`});naver.maps.Event.addListener(marker,'click',()=>toggleRecommendationPlace(p.name));recommendationMarkers.push(marker)})}loadNaverMap();
document.querySelector('#naverSearchBtn').addEventListener('click',searchNaverMap);document.querySelector('#builderSearch').addEventListener('keydown',e=>{if(e.key==='Enter')searchNaverMap()});document.querySelector('#builderResults').addEventListener('click',e=>{const btn=e.target.closest('.builder-result');if(!btn)return;const p=e.currentTarget._items?.[Number(btn.dataset.index)];if(!p)return;const existing=plans[currentDay].find(x=>x.name===p.name);if(existing){if(existing.marker)existing.marker.setMap(null);plans[currentDay]=plans[currentDay].filter(x=>x.name!==p.name);renderItinerary();searchNaverMap();showToast(`${p.name}을(를) 일정에서 제거했어요.`);return}const place={name:p.name,distance:'지도 기준',address:p.address,category:p.category,location:p.latitude&&p.longitude?new naver.maps.LatLng(p.latitude,p.longitude):null};if(window.naverMap&&place.location)place.marker=new naver.maps.Marker({map:window.naverMap,position:place.location,title:place.name});plans[currentDay].push(place);renderItinerary();searchNaverMap();showToast(`${place.name}을(를) ${currentDay}에 추가했어요.`)});
document.querySelector('#dayTabs').addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;document.querySelectorAll('#dayTabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');currentDay=btn.dataset.day;renderItinerary()});
document.querySelector('#itinerary').addEventListener('click',e=>{const btn=e.target.closest('.remove-place');if(btn){plans[currentDay].splice(Number(btn.dataset.index),1);renderItinerary()}});
document.querySelectorAll('.choice').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}));
document.querySelectorAll('.segmented').forEach(group=>group.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{group.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active')})));
document.querySelector('#recommendBtn').addEventListener('click',()=>{const style=document.querySelector('#styleChoices .active').dataset.style;const title=style==='tourist'?'대표 명소를 중심으로':style==='local'?'로컬의 결을 따라':style==='active'?'액티비티와 바다를':'대표와 로컬을 반반으로';document.querySelector('#resultTitle').textContent=title;renderRoutes(style==='mix'?routes:routes.filter(r=>r.style===style||r.style==='mix'));document.querySelector('.results').scrollIntoView({behavior:'smooth'});showToast('조건에 맞춰 코스와 예상 비용을 업데이트했어요.')});
searchInput.addEventListener('input',e=>renderSearch(e.target.value));
document.addEventListener('click',e=>{if(e.target.matches('.save')||e.target.id==='shareTop')showToast(e.target.id==='shareTop'?'공유 링크를 준비했어요. 카카오톡으로 보내보세요.':'일정을 저장했어요.');});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const type=b.textContent;if(type==='가격순')renderRoutes([...routes].sort((a,b)=>a.price-b.price));if(type==='거리순')renderRoutes([...routes].sort((a,b)=>parseFloat(a.distance)-parseFloat(b.distance)));showToast(`${type} 기준으로 정렬했어요.`)}));
function showToast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
function renderRecommendationMarkers(){recommendationMarkers.forEach(marker=>marker.setMap(null));recommendationMarkers=[];const unique=[...new Map(places.map(p=>[p.name,p])).values()];unique.forEach(p=>{if(plans[currentDay].some(x=>x.name===p.name))return;const coords=recommendationCoordinates[p.name];if(!coords)return;const marker=new naver.maps.Marker({map:window.naverMap,position:new naver.maps.LatLng(coords[0],coords[1]),title:`${p.name} · 클릭하여 일정에 추가`});naver.maps.Event.addListener(marker,'click',()=>toggleRecommendationPlace(p.name));recommendationMarkers.push(marker)})}
function toggleRecommendationPlace(name){const p=places.find(x=>x.name===name)||{name,type:'★',distance:'추천 코스'};const existing=plans[currentDay].find(x=>x.name===name);if(existing){if(existing.marker)existing.marker.setMap(null);plans[currentDay]=plans[currentDay].filter(x=>x.name!==name);showToast(`${name}을(를) ${currentDay}에서 제거했어요.`)}else{const coords=recommendationCoordinates[name];const location=coords?new naver.maps.LatLng(coords[0],coords[1]):null;plans[currentDay].push({name,distance:p.distance,address:'포항 추천 여행지',category:'추천 여행지',location});showToast(`${name}을(를) ${currentDay}에 추가했어요.`)}renderItinerary();renderRecommendationMarkers()}
function renderRecommendationMarkers(){recommendationMarkers.forEach(marker=>marker.setMap(null));recommendationMarkers=[];const unique=[...new Map(places.map(p=>[p.name,p])).values()];unique.forEach(p=>{const coords=recommendationCoordinates[p.name];if(!coords)return;const marker=new naver.maps.Marker({map:window.naverMap,position:new naver.maps.LatLng(coords[0],coords[1]),title:`${p.name} · 클릭하여 일정에 추가/제거`});naver.maps.Event.addListener(marker,'click',()=>{const existing=plans[currentDay].find(x=>x.name===p.name);if(existing){plans[currentDay]=plans[currentDay].filter(x=>x.name!==p.name);marker.setMap(null);renderItinerary();showToast(`${p.name}을(를) ${currentDay}에서 제거했어요.`)}else{plans[currentDay].push({name:p.name,distance:p.distance,address:'포항 추천 여행지',category:'추천 여행지',location:marker.getPosition(),marker});renderItinerary();showToast(`${p.name}을(를) ${currentDay}에 추가했어요.`)}});recommendationMarkers.push(marker)})}
function updatePlanMarkerNumbers(){plans[currentDay].forEach((place,index)=>{if(place.marker)place.marker.setIcon({content:`<div class="plan-marker"><span>${index+1}</span></div>`,anchor:new naver.maps.Point(15,15)})})}
const renderItineraryWithNumbers=renderItinerary;renderItinerary=function(){renderItineraryWithNumbers();updatePlanMarkerNumbers()};
let routeRequestId=0;renderDayRoute=async function(){const requestId=++routeRequestId;dayRouteOverlays.forEach(x=>x.setMap(null));dayRouteOverlays=[];if(!window.naverMap)return;const locations=plans[currentDay].map(p=>p.location).filter(Boolean);for(let i=1;i<locations.length;i++){const a=locations[i-1],b=locations[i];try{const response=await fetch(`/api/route?start=${a.lng()},${a.lat()}&goal=${b.lng()},${b.lat()}`);if(requestId!==routeRequestId)return;if(!response.ok)continue;const route=await response.json();const path=route.path.map(([lng,lat])=>new naver.maps.LatLng(lat,lng));dayRouteOverlays.push(new naver.maps.Polyline({map:window.naverMap,path,strokeColor:'#07526b',strokeWeight:5,strokeOpacity:.8,zIndex:20}));const midpoint=path[Math.floor(path.length/2)];dayRouteOverlays.push(new naver.maps.Marker({map:window.naverMap,position:midpoint,zIndex:30,icon:{content:`<div class="route-distance-label">${(route.distance/1000).toFixed(1)} km</div>`,anchor:new naver.maps.Point(0,0)}}))}catch(error){console.warn('도로 경로를 불러오지 못했습니다.',error)}}};
let dayRouteOverlays=[];function routeDistance(a,b){const rad=Math.PI/180,lat1=a.lat()*rad,lat2=b.lat()*rad,dLat=(b.lat()-a.lat())*rad,dLng=(b.lng()-a.lng())*rad;const h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}function renderDayRoute(){dayRouteOverlays.forEach(x=>x.setMap(null));dayRouteOverlays=[];if(!window.naverMap)return;const locations=plans[currentDay].map(p=>p.location).filter(Boolean);for(let i=1;i<locations.length;i++){const a=locations[i-1],b=locations[i],km=routeDistance(a,b);dayRouteOverlays.push(new naver.maps.Polyline({map:window.naverMap,path:[a,b],strokeColor:'#07526b',strokeWeight:4,strokeOpacity:.75,strokeStyle:'solid',zIndex:20}));const midpoint=new naver.maps.LatLng((a.lat()+b.lat())/2,(a.lng()+b.lng())/2);dayRouteOverlays.push(new naver.maps.Marker({map:window.naverMap,position:midpoint,zIndex:30,icon:{content:`<div class="route-distance-label">${km.toFixed(1)} km</div>`,anchor:new naver.maps.Point(0,0)}}))}}
const originalRenderItinerary=renderItinerary;renderItinerary=function(){originalRenderItinerary();renderDayRoute()};
