const routes=[
 {tag:'MIX · 추천 01',style:'mix',title:'바다와 동네 사이, 포항의 첫 장면',desc:'대표 명소와 로컬 쉼터를 자연스럽게 잇는 코스',time:'2박 3일',distance:'48.2 km',price:1764000,places:[['★','영일대 해수욕장','4.8 km'],['○','송도 솔밭','6.2 km'],['★','스페이스워크','9.4 km'],['○','청림동 카페','2.8 km']]},
 {tag:'LOCAL · 추천 02',style:'local',title:'파도 따라 천천히, 로컬의 주말',desc:'사람이 붐비지 않는 해안과 동네 식당 중심',time:'2박 3일',distance:'39.8 km',price:1586000,places:[['○','송도 솔밭','6.2 km'],['○','연오랑세오녀 테마공원','11.8 km'],['★','호미곶','24.5 km'],['○','구룡포 골목','8.1 km']]},
 {tag:'TOURIST · 추천 03',style:'tourist',title:'처음이라면 꼭, 포항 클래식',desc:'포항을 대표하는 장면을 빠짐없이 만나는 코스',time:'2박 3일',distance:'62.4 km',price:1832000,places:[['★','스페이스워크','9.4 km'],['★','영일대','4.8 km'],['★','호미곶','24.5 km'],['★','죽도시장','3.1 km']]},
 {tag:'ACTIVE · 추천 04',style:'active',title:'걷고 오르고, 바람을 타는 하루',desc:'액티비티와 전망 포인트를 밀도 있게 연결',time:'2박 3일',distance:'54.7 km',price:1718000,places:[['★','스페이스워크','9.4 km'],['○','내연산 트레킹','28.4 km'],['★','영일대','4.8 km'],['○','칠포 해변','17.3 km']]},
 {tag:'LOCAL · 추천 05',style:'local',title:'구룡포에서 만나는 포항의 결',desc:'근대문화 골목과 현지 식탁을 따라가는 코스',time:'2박 3일',distance:'58.1 km',price:1638000,places:[['★','구룡포 일본인 가옥거리','36.6 km'],['○','구룡포항','37.2 km'],['○','대보항','40.3 km'],['★','호미곶','24.5 km']]}
];
const places=[...new Map(routes.flatMap(r=>r.places.map(p=>[p[1],{name:p[1],type:p[0],distance:p[2],route:r.title}]))).values()];
const grid=document.querySelector('#routeGrid'), searchInput=document.querySelector('#placeSearch'), searchResults=document.querySelector('#searchResults');
const money=n=>`₩${n.toLocaleString('ko-KR')}`;
function renderRoutes(list=routes){grid.innerHTML=list.map((r,i)=>`<article class="route-card ${i===0?'featured':''}"><div class="route-top"><div><span class="route-tag">${r.tag}</span><h3>${r.title}</h3><p>${r.desc}</p></div><span>♡</span></div><div class="route-line"></div><div class="route-stats"><span>전체 이동 <strong>${r.distance}</strong></span><span>4명 예상 비용 <strong>${money(r.price)}</strong></span></div><div class="route-places">${r.places.map(p=>`<span class="place ${p[0]==='★'?'star':'circle'}">${p[0]} ${p[1]} <small>${p[2]}</small></span>`).join('')}</div><button class="save" aria-label="일정 저장">＋</button></article>`).join('')}
function renderSearch(query=''){const q=query.trim().toLowerCase();const found=places.filter(p=>!q||p.name.toLowerCase().includes(q)||p.route.toLowerCase().includes(q));searchResults.innerHTML=found.length?found.map(p=>`<button class="search-result"><span class="result-symbol">${p.type}</span><span><b>${p.name}</b><small>${p.route}</small></span><strong>${p.distance}</strong></button>`).join(''):`<p class="empty">검색 결과가 없어요. 예: 영일대, 호미곶, 카페</p>`;}
renderRoutes();renderSearch();
const plans={'1일차':[],'2일차':[],'3일차':[]};let currentDay='1일차';
function renderBuilderResults(q=''){const query=q.trim().toLowerCase();const found=places.filter(p=>!query||p.name.toLowerCase().includes(query)||p.route.toLowerCase().includes(query));document.querySelector('#builderResults').innerHTML=found.slice(0,8).map(p=>`<button class="builder-result" data-place="${p.name}"><span class="result-symbol">${p.type}</span><span><b>${p.name}</b><small>${p.route}</small></span><strong>${p.distance}</strong><span class="add-mark">＋</span></button>`).join('')}
function renderItinerary(){const list=plans[currentDay];document.querySelector('#selectedDay').textContent=`${currentDay} 일정`;document.querySelector('#selectedCount').textContent=`${list.length}곳`;document.querySelector('#itinerary').innerHTML=list.length?list.map((p,i)=>`<div class="itinerary-item"><span class="order">${i+1}</span><span><b>${p.name}</b><small>${p.distance} · 네이버 지도 장소</small></span><a href="https://map.naver.com/p/search/${encodeURIComponent(p.name)}" target="_blank" rel="noreferrer">지도 ↗</a><button class="remove-place" data-index="${i}">×</button></div>`).join(''):`<p class="empty">검색한 장소를 일정에 추가해보세요.</p>`}
renderBuilderResults();renderItinerary();
document.querySelector('#builderSearch').addEventListener('input',e=>renderBuilderResults(e.target.value));
document.querySelector('#builderResults').addEventListener('click',e=>{const btn=e.target.closest('.builder-result');if(!btn)return;const p=places.find(x=>x.name===btn.dataset.place);if(p&&!plans[currentDay].some(x=>x.name===p.name)){plans[currentDay].push(p);renderItinerary();showToast(`${p.name}을(를) ${currentDay}에 추가했어요.`)}});
document.querySelector('#dayTabs').addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;document.querySelectorAll('#dayTabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');currentDay=btn.dataset.day;renderItinerary()});
document.querySelector('#itinerary').addEventListener('click',e=>{const btn=e.target.closest('.remove-place');if(btn){plans[currentDay].splice(Number(btn.dataset.index),1);renderItinerary()}});
document.querySelectorAll('.choice').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}));
document.querySelectorAll('.segmented').forEach(group=>group.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{group.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active')})));
document.querySelector('#recommendBtn').addEventListener('click',()=>{const style=document.querySelector('#styleChoices .active').dataset.style;const title=style==='tourist'?'대표 명소를 중심으로':style==='local'?'로컬의 결을 따라':style==='active'?'액티비티와 바다를':'대표와 로컬을 반반으로';document.querySelector('#resultTitle').textContent=title;renderRoutes(style==='mix'?routes:routes.filter(r=>r.style===style||r.style==='mix'));document.querySelector('.results').scrollIntoView({behavior:'smooth'});showToast('조건에 맞춰 코스와 예상 비용을 업데이트했어요.')});
searchInput.addEventListener('input',e=>renderSearch(e.target.value));
document.addEventListener('click',e=>{if(e.target.matches('.save')||e.target.id==='shareTop')showToast(e.target.id==='shareTop'?'공유 링크를 준비했어요. 카카오톡으로 보내보세요.':'일정을 저장했어요.');});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const type=b.textContent;if(type==='가격순')renderRoutes([...routes].sort((a,b)=>a.price-b.price));if(type==='거리순')renderRoutes([...routes].sort((a,b)=>parseFloat(a.distance)-parseFloat(b.distance)));showToast(`${type} 기준으로 정렬했어요.`)}));
function showToast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
